// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.1
// source: staff-microservice.proto

package staff_protobuf

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StaffService_GetStaffMember_FullMethodName    = "/staff.StaffService/GetStaffMember"
	StaffService_GetCoursesList_FullMethodName    = "/staff.StaffService/GetCoursesList"
	StaffService_CreateStaffMember_FullMethodName = "/staff.StaffService/CreateStaffMember"
	StaffService_UpdateStaffMember_FullMethodName = "/staff.StaffService/UpdateStaffMember"
	StaffService_DeleteStaffMember_FullMethodName = "/staff.StaffService/DeleteStaffMember"
)

// StaffServiceClient is the client API for StaffService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StaffServiceClient interface {
	// Get a staff member
	GetStaffMember(ctx context.Context, in *GetStaffMemberRequest, opts ...grpc.CallOption) (*GetStaffMemberResponse, error)
	// Get all courses assigned to a staff member
	GetCoursesList(ctx context.Context, in *GetCoursesListRequest, opts ...grpc.CallOption) (*GetCoursesListResponse, error)
	// Create a new staff member
	CreateStaffMember(ctx context.Context, in *CreateStaffMemberRequest, opts ...grpc.CallOption) (*CreateStaffMemberResponse, error)
	// Update a staff member
	UpdateStaffMember(ctx context.Context, in *UpdateStaffMemberRequest, opts ...grpc.CallOption) (*UpdateStaffMemberResponse, error)
	// Delete a staff member
	DeleteStaffMember(ctx context.Context, in *DeleteStaffMemberRequest, opts ...grpc.CallOption) (*DeleteStaffMemberResponse, error)
}

type staffServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStaffServiceClient(cc grpc.ClientConnInterface) StaffServiceClient {
	return &staffServiceClient{cc}
}

func (c *staffServiceClient) GetStaffMember(ctx context.Context, in *GetStaffMemberRequest, opts ...grpc.CallOption) (*GetStaffMemberResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStaffMemberResponse)
	err := c.cc.Invoke(ctx, StaffService_GetStaffMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *staffServiceClient) GetCoursesList(ctx context.Context, in *GetCoursesListRequest, opts ...grpc.CallOption) (*GetCoursesListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCoursesListResponse)
	err := c.cc.Invoke(ctx, StaffService_GetCoursesList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *staffServiceClient) CreateStaffMember(ctx context.Context, in *CreateStaffMemberRequest, opts ...grpc.CallOption) (*CreateStaffMemberResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateStaffMemberResponse)
	err := c.cc.Invoke(ctx, StaffService_CreateStaffMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *staffServiceClient) UpdateStaffMember(ctx context.Context, in *UpdateStaffMemberRequest, opts ...grpc.CallOption) (*UpdateStaffMemberResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateStaffMemberResponse)
	err := c.cc.Invoke(ctx, StaffService_UpdateStaffMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *staffServiceClient) DeleteStaffMember(ctx context.Context, in *DeleteStaffMemberRequest, opts ...grpc.CallOption) (*DeleteStaffMemberResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteStaffMemberResponse)
	err := c.cc.Invoke(ctx, StaffService_DeleteStaffMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StaffServiceServer is the server API for StaffService service.
// All implementations must embed UnimplementedStaffServiceServer
// for forward compatibility.
type StaffServiceServer interface {
	// Get a staff member
	GetStaffMember(context.Context, *GetStaffMemberRequest) (*GetStaffMemberResponse, error)
	// Get all courses assigned to a staff member
	GetCoursesList(context.Context, *GetCoursesListRequest) (*GetCoursesListResponse, error)
	// Create a new staff member
	CreateStaffMember(context.Context, *CreateStaffMemberRequest) (*CreateStaffMemberResponse, error)
	// Update a staff member
	UpdateStaffMember(context.Context, *UpdateStaffMemberRequest) (*UpdateStaffMemberResponse, error)
	// Delete a staff member
	DeleteStaffMember(context.Context, *DeleteStaffMemberRequest) (*DeleteStaffMemberResponse, error)
	mustEmbedUnimplementedStaffServiceServer()
}

// UnimplementedStaffServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStaffServiceServer struct{}

func (UnimplementedStaffServiceServer) GetStaffMember(context.Context, *GetStaffMemberRequest) (*GetStaffMemberResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStaffMember not implemented")
}
func (UnimplementedStaffServiceServer) GetCoursesList(context.Context, *GetCoursesListRequest) (*GetCoursesListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCoursesList not implemented")
}
func (UnimplementedStaffServiceServer) CreateStaffMember(context.Context, *CreateStaffMemberRequest) (*CreateStaffMemberResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateStaffMember not implemented")
}
func (UnimplementedStaffServiceServer) UpdateStaffMember(context.Context, *UpdateStaffMemberRequest) (*UpdateStaffMemberResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateStaffMember not implemented")
}
func (UnimplementedStaffServiceServer) DeleteStaffMember(context.Context, *DeleteStaffMemberRequest) (*DeleteStaffMemberResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteStaffMember not implemented")
}
func (UnimplementedStaffServiceServer) mustEmbedUnimplementedStaffServiceServer() {}
func (UnimplementedStaffServiceServer) testEmbeddedByValue()                      {}

// UnsafeStaffServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StaffServiceServer will
// result in compilation errors.
type UnsafeStaffServiceServer interface {
	mustEmbedUnimplementedStaffServiceServer()
}

func RegisterStaffServiceServer(s grpc.ServiceRegistrar, srv StaffServiceServer) {
	// If the following call pancis, it indicates UnimplementedStaffServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StaffService_ServiceDesc, srv)
}

func _StaffService_GetStaffMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStaffMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StaffServiceServer).GetStaffMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StaffService_GetStaffMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StaffServiceServer).GetStaffMember(ctx, req.(*GetStaffMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StaffService_GetCoursesList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCoursesListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StaffServiceServer).GetCoursesList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StaffService_GetCoursesList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StaffServiceServer).GetCoursesList(ctx, req.(*GetCoursesListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StaffService_CreateStaffMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateStaffMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StaffServiceServer).CreateStaffMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StaffService_CreateStaffMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StaffServiceServer).CreateStaffMember(ctx, req.(*CreateStaffMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StaffService_UpdateStaffMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateStaffMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StaffServiceServer).UpdateStaffMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StaffService_UpdateStaffMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StaffServiceServer).UpdateStaffMember(ctx, req.(*UpdateStaffMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StaffService_DeleteStaffMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteStaffMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StaffServiceServer).DeleteStaffMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StaffService_DeleteStaffMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StaffServiceServer).DeleteStaffMember(ctx, req.(*DeleteStaffMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StaffService_ServiceDesc is the grpc.ServiceDesc for StaffService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StaffService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "staff.StaffService",
	HandlerType: (*StaffServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStaffMember",
			Handler:    _StaffService_GetStaffMember_Handler,
		},
		{
			MethodName: "GetCoursesList",
			Handler:    _StaffService_GetCoursesList_Handler,
		},
		{
			MethodName: "CreateStaffMember",
			Handler:    _StaffService_CreateStaffMember_Handler,
		},
		{
			MethodName: "UpdateStaffMember",
			Handler:    _StaffService_UpdateStaffMember_Handler,
		},
		{
			MethodName: "DeleteStaffMember",
			Handler:    _StaffService_DeleteStaffMember_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "staff-microservice.proto",
}
