// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.0
// 	protoc        v5.28.3
// source: staff-microservice.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request message for getting a staff member.
type GetStaffMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	StaffID       string                 `protobuf:"bytes,2,opt,name=staffID,proto3" json:"staffID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStaffMemberRequest) Reset() {
	*x = GetStaffMemberRequest{}
	mi := &file_staff_microservice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStaffMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStaffMemberRequest) ProtoMessage() {}

func (x *GetStaffMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_staff_microservice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStaffMemberRequest.ProtoReflect.Descriptor instead.
func (*GetStaffMemberRequest) Descriptor() ([]byte, []int) {
	return file_staff_microservice_proto_rawDescGZIP(), []int{0}
}

func (x *GetStaffMemberRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *GetStaffMemberRequest) GetStaffID() string {
	if x != nil {
		return x.StaffID
	}
	return ""
}

// Response message contains the staff member.
type GetStaffMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StaffMember   *StaffMember           `protobuf:"bytes,1,opt,name=staffMember,proto3" json:"staffMember,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStaffMemberResponse) Reset() {
	*x = GetStaffMemberResponse{}
	mi := &file_staff_microservice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStaffMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStaffMemberResponse) ProtoMessage() {}

func (x *GetStaffMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_staff_microservice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStaffMemberResponse.ProtoReflect.Descriptor instead.
func (*GetStaffMemberResponse) Descriptor() ([]byte, []int) {
	return file_staff_microservice_proto_rawDescGZIP(), []int{1}
}

func (x *GetStaffMemberResponse) GetStaffMember() *StaffMember {
	if x != nil {
		return x.StaffMember
	}
	return nil
}

// Request message for creating a new staff member.
type CreateStaffMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	StaffMember   *StaffMember           `protobuf:"bytes,2,opt,name=staffMember,proto3" json:"staffMember,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateStaffMemberRequest) Reset() {
	*x = CreateStaffMemberRequest{}
	mi := &file_staff_microservice_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStaffMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStaffMemberRequest) ProtoMessage() {}

func (x *CreateStaffMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_staff_microservice_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStaffMemberRequest.ProtoReflect.Descriptor instead.
func (*CreateStaffMemberRequest) Descriptor() ([]byte, []int) {
	return file_staff_microservice_proto_rawDescGZIP(), []int{2}
}

func (x *CreateStaffMemberRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *CreateStaffMemberRequest) GetStaffMember() *StaffMember {
	if x != nil {
		return x.StaffMember
	}
	return nil
}

// Response message contains the new staff member details.
type CreateStaffMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateStaffMemberResponse) Reset() {
	*x = CreateStaffMemberResponse{}
	mi := &file_staff_microservice_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStaffMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStaffMemberResponse) ProtoMessage() {}

func (x *CreateStaffMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_staff_microservice_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStaffMemberResponse.ProtoReflect.Descriptor instead.
func (*CreateStaffMemberResponse) Descriptor() ([]byte, []int) {
	return file_staff_microservice_proto_rawDescGZIP(), []int{3}
}

// Request message for updating a staff member.
type UpdateStaffMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	StaffMember   *StaffMember           `protobuf:"bytes,2,opt,name=staffMember,proto3" json:"staffMember,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStaffMemberRequest) Reset() {
	*x = UpdateStaffMemberRequest{}
	mi := &file_staff_microservice_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStaffMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStaffMemberRequest) ProtoMessage() {}

func (x *UpdateStaffMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_staff_microservice_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStaffMemberRequest.ProtoReflect.Descriptor instead.
func (*UpdateStaffMemberRequest) Descriptor() ([]byte, []int) {
	return file_staff_microservice_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateStaffMemberRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *UpdateStaffMemberRequest) GetStaffMember() *StaffMember {
	if x != nil {
		return x.StaffMember
	}
	return nil
}

// Request message with the updated staff member details.
type UpdateStaffMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStaffMemberResponse) Reset() {
	*x = UpdateStaffMemberResponse{}
	mi := &file_staff_microservice_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStaffMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStaffMemberResponse) ProtoMessage() {}

func (x *UpdateStaffMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_staff_microservice_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStaffMemberResponse.ProtoReflect.Descriptor instead.
func (*UpdateStaffMemberResponse) Descriptor() ([]byte, []int) {
	return file_staff_microservice_proto_rawDescGZIP(), []int{5}
}

// Request message for deleting a staff member.
type DeleteStaffMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	StaffID       string                 `protobuf:"bytes,2,opt,name=staffID,proto3" json:"staffID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteStaffMemberRequest) Reset() {
	*x = DeleteStaffMemberRequest{}
	mi := &file_staff_microservice_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteStaffMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteStaffMemberRequest) ProtoMessage() {}

func (x *DeleteStaffMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_staff_microservice_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteStaffMemberRequest.ProtoReflect.Descriptor instead.
func (*DeleteStaffMemberRequest) Descriptor() ([]byte, []int) {
	return file_staff_microservice_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteStaffMemberRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *DeleteStaffMemberRequest) GetStaffID() string {
	if x != nil {
		return x.StaffID
	}
	return ""
}

// Response message for deleting a staff member - no data returned.
type DeleteStaffMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteStaffMemberResponse) Reset() {
	*x = DeleteStaffMemberResponse{}
	mi := &file_staff_microservice_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteStaffMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteStaffMemberResponse) ProtoMessage() {}

func (x *DeleteStaffMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_staff_microservice_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteStaffMemberResponse.ProtoReflect.Descriptor instead.
func (*DeleteStaffMemberResponse) Descriptor() ([]byte, []int) {
	return file_staff_microservice_proto_rawDescGZIP(), []int{7}
}

// StaffMember message includes:
type StaffMember struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StaffID       string                 `protobuf:"bytes,1,opt,name=staffID,proto3" json:"staffID,omitempty"`
	FirstName     string                 `protobuf:"bytes,2,opt,name=firstName,proto3" json:"firstName,omitempty"`
	SecondName    string                 `protobuf:"bytes,3,opt,name=secondName,proto3" json:"secondName,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,5,opt,name=phoneNumber,proto3" json:"phoneNumber,omitempty"`
	Title         string                 `protobuf:"bytes,6,opt,name=title,proto3" json:"title,omitempty"`
	Office        string                 `protobuf:"bytes,7,opt,name=office,proto3" json:"office,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StaffMember) Reset() {
	*x = StaffMember{}
	mi := &file_staff_microservice_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StaffMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StaffMember) ProtoMessage() {}

func (x *StaffMember) ProtoReflect() protoreflect.Message {
	mi := &file_staff_microservice_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StaffMember.ProtoReflect.Descriptor instead.
func (*StaffMember) Descriptor() ([]byte, []int) {
	return file_staff_microservice_proto_rawDescGZIP(), []int{8}
}

func (x *StaffMember) GetStaffID() string {
	if x != nil {
		return x.StaffID
	}
	return ""
}

func (x *StaffMember) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *StaffMember) GetSecondName() string {
	if x != nil {
		return x.SecondName
	}
	return ""
}

func (x *StaffMember) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *StaffMember) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *StaffMember) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *StaffMember) GetOffice() string {
	if x != nil {
		return x.Office
	}
	return ""
}

var File_staff_microservice_proto protoreflect.FileDescriptor

var file_staff_microservice_proto_rawDesc = []byte{
	0x0a, 0x18, 0x73, 0x74, 0x61, 0x66, 0x66, 0x2d, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x73, 0x74, 0x61, 0x66,
	0x66, 0x22, 0x47, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x66, 0x66, 0x4d, 0x65, 0x6d,
	0x62, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x12, 0x18, 0x0a, 0x07, 0x73, 0x74, 0x61, 0x66, 0x66, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x73, 0x74, 0x61, 0x66, 0x66, 0x49, 0x44, 0x22, 0x4e, 0x0a, 0x16, 0x47, 0x65,
	0x74, 0x53, 0x74, 0x61, 0x66, 0x66, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x34, 0x0a, 0x0b, 0x73, 0x74, 0x61, 0x66, 0x66, 0x4d, 0x65, 0x6d,
	0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x73, 0x74, 0x61, 0x66,
	0x66, 0x2e, 0x53, 0x74, 0x61, 0x66, 0x66, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x0b, 0x73,
	0x74, 0x61, 0x66, 0x66, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x66, 0x0a, 0x18, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x53, 0x74, 0x61, 0x66, 0x66, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x34, 0x0a, 0x0b,
	0x73, 0x74, 0x61, 0x66, 0x66, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x12, 0x2e, 0x73, 0x74, 0x61, 0x66, 0x66, 0x2e, 0x53, 0x74, 0x61, 0x66, 0x66, 0x4d,
	0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x0b, 0x73, 0x74, 0x61, 0x66, 0x66, 0x4d, 0x65, 0x6d, 0x62,
	0x65, 0x72, 0x22, 0x1b, 0x0a, 0x19, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x74, 0x61, 0x66,
	0x66, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x66, 0x0a, 0x18, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x74, 0x61, 0x66, 0x66, 0x4d, 0x65,
	0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x12, 0x34, 0x0a, 0x0b, 0x73, 0x74, 0x61, 0x66, 0x66, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x73, 0x74, 0x61, 0x66, 0x66, 0x2e, 0x53,
	0x74, 0x61, 0x66, 0x66, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x0b, 0x73, 0x74, 0x61, 0x66,
	0x66, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x1b, 0x0a, 0x19, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x53, 0x74, 0x61, 0x66, 0x66, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x4a, 0x0a, 0x18, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x74,
	0x61, 0x66, 0x66, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x74, 0x61, 0x66, 0x66, 0x49,
	0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x74, 0x61, 0x66, 0x66, 0x49, 0x44,
	0x22, 0x1b, 0x0a, 0x19, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x74, 0x61, 0x66, 0x66, 0x4d,
	0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0xcb, 0x01,
	0x0a, 0x0b, 0x53, 0x74, 0x61, 0x66, 0x66, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x18, 0x0a,
	0x07, 0x73, 0x74, 0x61, 0x66, 0x66, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x73, 0x74, 0x61, 0x66, 0x66, 0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x69, 0x72, 0x73,
	0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x65, 0x63, 0x6f, 0x6e,
	0x64, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x20, 0x0a, 0x0b, 0x70,
	0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x14, 0x0a,
	0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69,
	0x74, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x69, 0x63, 0x65, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x69, 0x63, 0x65, 0x32, 0xe5, 0x02, 0x0a, 0x0c,
	0x53, 0x74, 0x61, 0x66, 0x66, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4d, 0x0a, 0x0e,
	0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x66, 0x66, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x1c,
	0x2e, 0x73, 0x74, 0x61, 0x66, 0x66, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x66, 0x66, 0x4d,
	0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x73,
	0x74, 0x61, 0x66, 0x66, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x66, 0x66, 0x4d, 0x65, 0x6d,
	0x62, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x56, 0x0a, 0x11, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x74, 0x61, 0x66, 0x66, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72,
	0x12, 0x1f, 0x2e, 0x73, 0x74, 0x61, 0x66, 0x66, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53,
	0x74, 0x61, 0x66, 0x66, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x20, 0x2e, 0x73, 0x74, 0x61, 0x66, 0x66, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x53, 0x74, 0x61, 0x66, 0x66, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x56, 0x0a, 0x11, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x74, 0x61,
	0x66, 0x66, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x1f, 0x2e, 0x73, 0x74, 0x61, 0x66, 0x66,
	0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x74, 0x61, 0x66, 0x66, 0x4d, 0x65, 0x6d, 0x62,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x73, 0x74, 0x61, 0x66,
	0x66, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x74, 0x61, 0x66, 0x66, 0x4d, 0x65, 0x6d,
	0x62, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x56, 0x0a, 0x11, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x74, 0x61, 0x66, 0x66, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72,
	0x12, 0x1f, 0x2e, 0x73, 0x74, 0x61, 0x66, 0x66, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53,
	0x74, 0x61, 0x66, 0x66, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x20, 0x2e, 0x73, 0x74, 0x61, 0x66, 0x66, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x53, 0x74, 0x61, 0x66, 0x66, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x2f, 0x5a, 0x2d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x42, 0x65, 0x74, 0x74, 0x65, 0x72, 0x47, 0x52, 0x2f, 0x73, 0x74, 0x61, 0x66, 0x66,
	0x2d, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_staff_microservice_proto_rawDescOnce sync.Once
	file_staff_microservice_proto_rawDescData = file_staff_microservice_proto_rawDesc
)

func file_staff_microservice_proto_rawDescGZIP() []byte {
	file_staff_microservice_proto_rawDescOnce.Do(func() {
		file_staff_microservice_proto_rawDescData = protoimpl.X.CompressGZIP(file_staff_microservice_proto_rawDescData)
	})
	return file_staff_microservice_proto_rawDescData
}

var file_staff_microservice_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_staff_microservice_proto_goTypes = []any{
	(*GetStaffMemberRequest)(nil),     // 0: staff.GetStaffMemberRequest
	(*GetStaffMemberResponse)(nil),    // 1: staff.GetStaffMemberResponse
	(*CreateStaffMemberRequest)(nil),  // 2: staff.CreateStaffMemberRequest
	(*CreateStaffMemberResponse)(nil), // 3: staff.CreateStaffMemberResponse
	(*UpdateStaffMemberRequest)(nil),  // 4: staff.UpdateStaffMemberRequest
	(*UpdateStaffMemberResponse)(nil), // 5: staff.UpdateStaffMemberResponse
	(*DeleteStaffMemberRequest)(nil),  // 6: staff.DeleteStaffMemberRequest
	(*DeleteStaffMemberResponse)(nil), // 7: staff.DeleteStaffMemberResponse
	(*StaffMember)(nil),               // 8: staff.StaffMember
}
var file_staff_microservice_proto_depIdxs = []int32{
	8, // 0: staff.GetStaffMemberResponse.staffMember:type_name -> staff.StaffMember
	8, // 1: staff.CreateStaffMemberRequest.staffMember:type_name -> staff.StaffMember
	8, // 2: staff.UpdateStaffMemberRequest.staffMember:type_name -> staff.StaffMember
	0, // 3: staff.StaffService.GetStaffMember:input_type -> staff.GetStaffMemberRequest
	2, // 4: staff.StaffService.CreateStaffMember:input_type -> staff.CreateStaffMemberRequest
	4, // 5: staff.StaffService.UpdateStaffMember:input_type -> staff.UpdateStaffMemberRequest
	6, // 6: staff.StaffService.DeleteStaffMember:input_type -> staff.DeleteStaffMemberRequest
	1, // 7: staff.StaffService.GetStaffMember:output_type -> staff.GetStaffMemberResponse
	3, // 8: staff.StaffService.CreateStaffMember:output_type -> staff.CreateStaffMemberResponse
	5, // 9: staff.StaffService.UpdateStaffMember:output_type -> staff.UpdateStaffMemberResponse
	7, // 10: staff.StaffService.DeleteStaffMember:output_type -> staff.DeleteStaffMemberResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_staff_microservice_proto_init() }
func file_staff_microservice_proto_init() {
	if File_staff_microservice_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_staff_microservice_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_staff_microservice_proto_goTypes,
		DependencyIndexes: file_staff_microservice_proto_depIdxs,
		MessageInfos:      file_staff_microservice_proto_msgTypes,
	}.Build()
	File_staff_microservice_proto = out.File
	file_staff_microservice_proto_rawDesc = nil
	file_staff_microservice_proto_goTypes = nil
	file_staff_microservice_proto_depIdxs = nil
}
